apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-enrollmentkitservices
  namespace: oc-projects
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: oc-enrollmentkitservices
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    labels:
        deployment: oc-enrollmentkitservices
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: oc-enrollmentkitservices-conf-unit
        image: image-registry.openshift-image-registry.svc:5000/s2i-eks/enrollmentkitservices@sha256:df3e295bf5e7a878d7ba5ac2fdada309ca56a4dc72dd06108ce6f8950a249c65
        imagePullPolicy: IfNotPresent
        name: enrollmentkitservices
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
